image:
  pullPolicy: Always
  tag: ""

service:
  type: LoadBalancer
  port: 9090

ingress:
  enabled: false
  annotations: {}
  paths: ["/"]
  hosts:
    - dev-flow-demo.k8s.bastianhofmann.de
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
