---
apiVersion: v1
kind: Namespace
metadata:
  name: {{build.profile.namespace}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{service.name}}
  namespace: {{build.profile.namespace}}
spec:
  selector:
    app: {{service.name}}
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{service.name}}
  namespace: {{build.profile.namespace}}
spec:
  replicas: 2
  selector:
    matchLabels: {app: {{service.name}}}
  revisionHistoryLimit: 1
  template:
    metadata:
      labels: {app: {{service.name}}}
      name: {{service.name}}
    spec:
      containers:
      - image: {{build.images["Dockerfile"]}}
        name: {{service.name}}
