docker_build('bashofmann/k8s-workshop-hello-svc', './src/hello-svc')

hello_svc_yaml = local('helm template helm-charts/hello-svc --name hello-svc -f ./hello-svc-values.yaml')

k8s_yaml(hello_svc_yaml)


docker_build('bashofmann/k8s-workshop-quote-svc', './src/quote-svc')

quote_svc_yaml = local('helm template helm-charts/quote-svc --name quote-svc -f ./quote-svc-values.yaml')

k8s_yaml(quote_svc_yaml)


docker_build('bashofmann/k8s-workshop-web-application', './src/web-application')

k8s_yaml(listdir('./src/web-application/deployment'))

k8s_resource('web-application', port_forwards="8080:80")
