name: web

profiles:
  default:
    hostname: dev-flow-demo.k8s.bastianhofmann.de
    namespace: dev-flow-demo
  stage:
    hostname: dev-flow-demo-stage.k8s.bastianhofmann.de
    namespace: dev-flow-demo-stage

requires:
- hello-svc
- quote-svc
