name: web

profiles:
  default:
    hostname: dev-flow-demo.bastian.plgrnd.be
    namespace: dev-flow-demo
  stage:
    hostname: dev-flow-demo-stage.bastian.plgrnd.be
    namespace: dev-flow-demo-stage

requires:
- hello-svc
- quote-svc
